name: Deploy to Prod (Master)
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Prod
      run: |
        echo "Deploy to Production"
        ls -la
