name: Deploy to Staging (Master)
on:
  push:
    branches:
      - master
    tags:
      - '!refs/tags/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to Staging
      run: |
        echo "Deploy to Staging"
        ls -la
